name: Notify 

on:
  pull_request:
    paths:
      - 'a.md'
      - 'c.md'

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Create Comment
      run: |
        # Use GitHub API to create a comment on the PR
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT="CC @NathanReb"
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
